import 'package:flutter/material.dart';
import 'package:outliner/generated/l10n/app_localizations.dart';
import 'package:outliner/ui/home_page.dart';
import 'package:outliner/ui/settings_page.dart';
import 'package:outliner/utils/toc_converter.dart';
import 'package:outliner/utils/font_manager.dart';
import 'package:shared_preferences/shared_preferences.dart';

class OutlinerApp extends StatefulWidget {
  const OutlinerApp({super.key});

  @override
  State<OutlinerApp> createState() => _OutlinerAppState();
}

class _OutlinerAppState extends State<OutlinerApp> {
  ThemeMode _themeMode = ThemeMode.system;
  Locale? _locale;
  List<TextEditingController> _levelControllers = [];
  bool _trimLines = true;
  int _selectedIndex = 0;

  static const _prefsKey = 'themeMode';
  static const _localePrefsKey = 'locale';

  @override
  void initState() {
    super.initState();
    _loadThemeMode();
    _loadLocale();
    _initLevelControllers();
  }

  void _initLevelControllers() {
    _levelControllers = List.generate(
      TocConverter.defaultLevelExpressions.length,
      (index) => TextEditingController(
          text: TocConverter.defaultLevelExpressions[index]),
    );
  }

  Future<void> _loadThemeMode() async {
    final prefs = await SharedPreferences.getInstance();
    final stored = prefs.getString(_prefsKey) ?? 'system';
    setState(() {
      _themeMode = _stringToThemeMode(stored);
    });
  }

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final stored = prefs.getString(_localePrefsKey) ?? 'system';
    setState(() {
      _locale = (stored == 'system') ? null : Locale(stored);
    });
  }

  ThemeMode _stringToThemeMode(String s) {
    switch (s) {
      case 'light':
        return ThemeMode.light;
      case 'dark':
        return ThemeMode.dark;
      default:
        return ThemeMode.system;
    }
  }

  String _themeModeToString(ThemeMode mode) {
    switch (mode) {
      case ThemeMode.light:
        return 'light';
      case ThemeMode.dark:
        return 'dark';
      default:
        return 'system';
    }
  }

  Future<void> _updateThemeMode(ThemeMode mode) async {
    setState(() {
      _themeMode = mode;
    });
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsKey, _themeModeToString(mode));
  }

  Future<void> _updateLocale(Locale? locale) async {
    setState(() {
      _locale = locale;
    });
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(
        _localePrefsKey, locale == null ? 'system' : locale.languageCode);
  }

  @override
  void dispose() {
    for (final c in _levelControllers) {
      c.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // 创建统一的文本主题，支持中文
    final textTheme = FontManager.createTextTheme(
      ThemeData.light().textTheme,
      useCJK: true,
    );

    final lightTheme = ThemeData.light().copyWith(
      textTheme: textTheme,
      appBarTheme: FontManager.createAppBarTheme(textTheme),
    );

    final darkTheme = ThemeData.dark().copyWith(
      textTheme: FontManager.createTextTheme(
        ThemeData.dark().textTheme,
        useCJK: true,
      ),
      appBarTheme: FontManager.createAppBarTheme(
        FontManager.createTextTheme(
          ThemeData.dark().textTheme,
          useCJK: true,
        ),
      ),
    );

    return MaterialApp(
      title: 'Outliner',
      // Localization delegates and supported locales generated by flutter gen_l10n
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      locale: _locale,
      theme: lightTheme,
      darkTheme: darkTheme,
      themeMode: _themeMode,
      home: Scaffold(
        body: IndexedStack(
          index: _selectedIndex,
          children: [
            AppHome(
              levelControllers: _levelControllers,
              trimLines: _trimLines,
              onTrimLinesChanged: (v) {
                setState(() {
                  _trimLines = v;
                });
              },
            ),
            SettingsPage(
              levelControllers: _levelControllers,
              trimLines: _trimLines,
              onTrimLinesChanged: (v) {
                setState(() {
                  _trimLines = v;
                });
              },
              currentThemeMode: _themeMode,
              onThemeModeChanged: (m) => _updateThemeMode(m),
              currentLanguage: _locale?.languageCode,
              onLanguageChanged: (lang) =>
                  _updateLocale(lang == 'system' ? null : Locale(lang)),
            ),
          ],
        ),
        bottomNavigationBar: BottomNavigationBar(
          type: BottomNavigationBarType.fixed,
          currentIndex: _selectedIndex,
          onTap: (i) => setState(() => _selectedIndex = i),
          showSelectedLabels: false,
          showUnselectedLabels: false,
          items: const [
            BottomNavigationBarItem(icon: Icon(Icons.home), label: ''),
            BottomNavigationBarItem(icon: Icon(Icons.settings), label: ''),
          ],
        ),
      ),
    );
  }
}
